### ISSUE TITLE
Failed to set ntp: NTP not supported.

### ISSUE THREAD

**Issue by FreedomPrevails** [seriyps/mtproto_proxy#33]
Tried to install on CentOS 7 using the interactive script. script was giving this error `Failed to set ntp: NTP not supported.` and exiting.
Installing ntp package resolved the issue. `yum install ntp`
`ntp` should be added to prerequisite packages.

**Comment by seriyps** [comment]
This is strange, because what script does is that it tries to disable `ntp` service and use `systemd-timesyncd`:

https://gist.github.com/seriyps/dc00ad91bfd8a2058f30845cd0daed83#file-mtp_install-sh-L142-L149

Do you have script's output available before it failed? I'm interested in the last `INFO` message it printed before it failed (basically, want to find which command crashed)

**Comment by FreedomPrevails** [comment]
Unfortunately I dont have the output. but I know exactly where it was failing as I debugged it.
`systemctl is-active ntp` was returning `unknown` and `timedatectl set-ntp on` was giving `Failed to set ntp: NTP not supported.` error and crashing the script.

**Comment by FreedomPrevails** [comment]
So this command was crashing the script `timedatectl set-ntp on`

**Comment by seriyps** [comment]
Ok, thanks! That's interesting.. I found this https://bugzilla.novell.com/show_bug.cgi?id=869336 but will investigate further later

**Comment by seriyps** [comment]
Also this: https://unix.stackexchange.com/questions/317346/ntp-not-enabled-according-to-timedatectl-centos-7

**Comment by seriyps** [comment]
It seems that, while Ubuntu uses systemd-timesyncd for time synchronization, CentOS 7 uses `ntp` or `chrony`.
I will update setup script to install `chrony` package.

**Comment by FreedomPrevails** [comment]
Well I dont know about `chrony`, but installing `ntp` resolved the issue for me.

**Comment by seriyps** [comment]
yep, `timedatectl` can work with both `ntp` and `chrony`. It checks which one is installed and uses it. And if none installed, then you'll get this error: `Failed to set ntp: NTP not supported.`

**Comment by rooted-script** [comment]
sudo ntpdate -qu 1.ro.pool.ntp.org
timedatectl set-timezone "your loc"

**Comment by C0d3-R3d** [comment]
I tried few thing but it doesn't work because "ntpd.service" doesn't exist/missing from.
so i reinstall "ntp" 
& also install "systemd-timesyncd"
Which synced with my system automatically. ANd now ntp is active without "timedatectl set-ntp on". 
may be it occurs because of some packet downloading issue while installing. It worked for me, I Hope this will work for you guys too.
