### ISSUE TITLE
limit on secret

### ISSUE THREAD

**Issue by karimi12** [seriyps/mtproto_proxy#46]
how can i limit connection on a secret?
or is possible see count connection on a secret in logs?

**Comment by seriyps** [comment]
Yes, it's quite easy to do with "policies". It's similar to this recipe https://github.com/seriyps/mtproto_proxy#limit-max-connections-to-proxy-port-from-single-ip

but instead of

```
{mtproto_proxy,
 [
  {policy,
    [{max_connections, [port_name, client_ipv4], 100}]},
  {ports,
    <..>
```

you should use just `port_name`:

```
{mtproto_proxy,
 [
  {policy,
    [{max_connections, [port_name], 100}]},
  {ports,
    <..>
```

This way you will limit max number of connections per-port. Erlang proxy doesn't allow to use more than one secret on single port.
