### ISSUE TITLE
The number of users connected to the proxy

### ISSUE THREAD

**Issue by jack-manual** [seriyps/mtproto_proxy#86]
Is there a way to know the number of users connected to the proxy?

Thanks

**Comment by seriyps** [comment]
It's not possible to know the number of unique Telegram accounts connected to the proxy, but you can get the number of network connections from clients to proxy. The problem is that each Telegram app creates multiple (3-10) connections to the proxy, so you may only estimate the number of users, see: https://github.com/seriyps/mtproto_proxy#helpers

You may also try to count the number of unique IPs connected to proxy port using Linux tools like `netstat` or `ss`

**Comment by jack-manual** [comment]
thank you so much
